ktor:
  deployment:
    port: 8080
  application:
    modules:
      - com.projectlumina.CorsKt.installCors
      - com.projectlumina.SerializationKt.configureSerialization
      - com.projectlumina.ExposedKt.configureExposed
      - com.projectlumina.RoutingKt.configureRouting
