ktor:
  deployment:
    port: 8080
  application:
    modules:
      - com.projectlumina.plugins.CorsKt.installCors
      - com.projectlumina.plugins.SerializationKt.configureSerialization
      - com.projectlumina.plugins.DatabaseKt.configureDatabase
      - com.projectlumina.plugins.RoutingKt.configureRouting
